# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleAPIFetchingExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleAPIFetchingExample

	#Project Utilities
	pod 'SwiftLint'
        pod 'R.swift'

	# Networking
	pod 'Moya'
        pod 'Wormholy', :configurations => ['Debug']

	pod 'Nuke'


  target 'SimpleAPIFetchingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
